<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# Here is the input for two matrices A & B 
a = [[1, 3],[2 ,5 ]]
b = [[1, 0 ,0 , 9, 0],[0 ,1, 0, 0, 0]]
r = int(0)
k = int(0)
o = []
n = []
if len(a[0])==len(b) :
    for i in range(0,len(a)) :
        for k in range(0,len(b[0])) :
            for j in range(0,len(a[i])):
                r = r+a[i][j]*b[j][k]
            o.append(r)
            r = 0
        n.append(o)
        o = []
        
else :
    print('not possible')
# Here is the product of two matrices
print(n)

[[1, 3, 0, 9, 0], [2, 5, 0, 18, 0]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [ ]:
import random
import numpy
# Input for selecting random number
l = [0,5,27,6,13,28,100,45,10,79]
g = int()
for i in range(0,len(l)):
    g = l[i] + g

f = int()
s = []
m = int()
for i in range(0,len(l)):
    f = l[i]/g
    m = m + f 
    s.append(m)

o = []
t = int()
h = int()
r = numpy.random.uniform(0,1,100)
for i in range(100):
    a = random.random()
    for j in range (0,len(l)):
        if a <= s[j] :
            print(l[j])
            break
        
            
            
            

    

        

100
79
13
45
79
45
79
100
79
100
79
79
27
79
45
100
79
100
28
27
79
27
100
45
45
28
100
79
45
45
100
28
100
100
79
100
79
45
100
79
79
27
79
79
28
10
100
79
28
100
100
79
79
45
27
79
27
79
6
45
100
100
45
100
28
100
45
27
100
100
79
100
28
27
79
100
28
79
100
5
100
79
79
79
5
28
79
79
27
5
79
100
79
79
10
100
100
45
100
79


<h3> Q3: Replace the digits in the string with #</h3>

Consider a string that will have digits in that, we need to remove all the characters which are not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
r = input()
# source stackoverflow
s = ''.join('#' for x in r if x.isdigit())
print(s)
# here is the input and below is the output   

#2a$#b%c%561#
####


<h3> Q4: Students marks dashboard</h3>

Consider the marks list of class students given in two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on. <br><br>

Your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks.</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

a. 
student8  98
student10 80
student2  78
student5  48
student7  47

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
# Here are the inputs for the student and marks in list l and Marks
l =  ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80]
mapm = {}
for i in range(0,len(l)-1) :
    mapm[l[i]] = Marks[i]
    
print(mapm)
# Who got top 5 ranks, in the descending order of marks
sortedByValue = sorted(mapm.items(), key = 
             lambda kv:(kv[1], kv[0]), reverse=True)
r = sortedByValue[0:5]
print('top 5 ranks, in the descending order of marks',r)
# Who got least 5 ranks, in the increasing order of marks
sortedByValue = sorted(mapm.items(), key = 
             lambda kv:(kv[1], kv[0]), )
f = sortedByValue[0:5]
print('least 5 ranks, in the increasing order of marks',f)
# Who got marks between >25th percentile <75th percentile, in the increasing order of marks
sortedByValue = sorted(mapm.items(), key = 
             lambda kv:(kv[1], kv[0]), )
o = sortedByValue[int(len(l)/4):int(len(l)*3/4)]
print('marks between >25th percentile <75th percentile, in the increasing order of marks',o)

{'student1': 45, 'student2': 78, 'student3': 12, 'student4': 14, 'student5': 48, 'student6': 43, 'student7': 45, 'student8': 98, 'student9': 35}
top 5 ranks, in the descending order of marks [('student8', 98), ('student2', 78), ('student5', 48), ('student7', 45), ('student1', 45)]
least 5 ranks, in the increasing order of marks [('student3', 12), ('student4', 14), ('student9', 35), ('student6', 43), ('student1', 45)]
marks between >25th percentile <75th percentile, in the increasing order of marks [('student9', 35), ('student6', 43), ('student1', 45), ('student7', 45), ('student5', 48)]


<h3> Q5: Find the closest points</h3>

Consider you are given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P

<br>Cosine distance between two points (x,y) and (p,q) is defined as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:
import math
# Inputs of near points in S and point we are dealing with in P
S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
listr = [list(elem) for elem in S]
p = int()
l = []
# using the cosine formula
for i in range(0,len(S)):
    p = math.degrees (math.acos (((P[0]*S[i][0])+(P[1]*S[i][1]))/(math.sqrt((S[i][0]*S[i][0])+(S[i][1]*S[i][1]))*(math.sqrt((P[0]*P[0])+(P[1]*P[1]))))))
    l.append(p)
maps = {}
for i in range (0,len(listr)):
    maps[l[i]]=listr[i]
sortedByValue = sorted(maps.items(), key = 
             lambda kv:(kv[0], kv[1]))
r = sortedByValue[0:5]
j = []
for i in range(0,len(r)):
    j.append(r[i][1])
# printing the top five points having highest cosine value
print(j)


    


[[6, -7], [1, -1], [6, 0], [-5, -8], [-1, -1]]


<h3> Q6: Find which line separates oranges and apples</h3>

Consider you are given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string format, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: You need to do string parsing here and get the coefficients of x,y and intercept.
</pre>
Your task here is to print "YES"/"NO" for each line given. You should print YES, if all the red points are one side of the line and blue points are on other side of the line, otherwise you should print NO.
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
import re
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
r = []
k = []
# Splitting the lines with x and y to get coefficient and intercept
for i in range(0, len(Lines)):
    r = re.split("x|y",Lines[i])
    k.append(r)
# putting the values x and y of red point in lines and getting the magnitude
d = []
for i in range(0,len(k)):
    a = []
    for j in range(0,len(Red)):
        m = int(float(Red[j][0])*float(k[i][0])+float(Red[j][1])*float(k[i][1])+float(k[i][2]))
        a.append(m)
    d.append(a)
# putting the values x and y of red point in lines and getting the magnitude
g = []
for i in range(0,len(k)):
    o = []
    for j in range(0,len(Red)):
        u = int(float(Blue[j][0])*float(k[i][0])+float(Blue[j][1])*float(k[i][1])+float(k[i][2]))
        o.append(u)
    g.append(o)
# Rejecting the line if the magnitude of value a*x(R)+b*y(R)+c is either >0 or <0 for all points x(R),y(R) in red 
for i in range(0,len(d)): 
    test = 1
    if d[i][0]<0:
        test = -1
    for j in range(1,len(d[i])):
        if test*d[i][j]<0 : 
            print('no')
            break
    teste = 1
    if g[i][0]<0:
        teste = -1
# Selecting all the lines for which red and blue points are gives opposite sign values of ax+by+c 
    for j in range(1,len(g[i])):
        if teste*g[i][j]<0 :
            break
    if j==len(g[i])-1 and test*teste<0:
        print('yes')

yes
no
no
yes


<h3> Q7: Filling the missing values in the specified format</h3>

You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 

<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [ ]:
# Here is the input
input = [[_,_,_,24],[40,_,_,_,60],[80,_,_,_,_],[_,_,30,_,_,_,50,_,_]]
for i in range(0,len(input)):
    m = input[i]
    r = []
    a = int(0)
    if m[0]==_:
        m[0]=0
    for i in range(1,len(m)):
        if m[i]!=_:
            m[i]=(m[i]+m[a])/(i-a+1)
            r.append([m[i]]*(i-a))
            a = i
    if m[len(m)-1]==_:
        m[a]=m[a]/(len(m)-a)
        r.append([m[a]]*(len(m)-a))
    k = sum(r,[])
    print(k)
        

[6.0, 6.0, 6.0]
[20.0, 20.0, 20.0, 20.0]
[16.0, 16.0, 16.0, 16.0, 16.0]
[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


<h3> Q8: Find the probabilities</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. The first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. The second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>



In [ ]:
# Here is the input list 
e = [["F1","S1"],["F2","S2"],["F3","S3"],["F1","S2"],["F2","S3"],["F3","S2"],["F2","S1"],["F4","S1"],["F4","S3"],["F5","S1"]]
# Calculating probability of F1,F2,F3,F4,F5 when S1 has already occured
l = []
w = []
for i in range(0,len(e)):
    if e[i][1]=="S1":
        w.append('S1')
l.append(len(w))
x = []
for i in range(0,len(e)):
    if e[i][1]=="S2":
        x.append('S2')
l.append(len(x))
y = []
for i in range(0,len(e)):
    if e[i][1]=="S3":
        y.append('S3')
l.append(len(y))
g = ['F1','F2','F3','F4','F5']
arr = [[0 for x in range(6)] for y in range(6)]
s1 = 0
s2 = 0
s3 = 0
#print("yu:"+e[0][0][1:-1])
for i in range (0,len(e)):
    if e[i][1]=="S1":
        arr[int(e[i][0][1:2])-1][0]=arr[int(e[i][0][1:2])-1][0]+1
        s1=s1+1
    elif e[i][1]=="S2":
        arr[int(e[i][0][1:2])-1][1]=arr[int(e[i][0][1:2])-1][1]+1
        s2=s2+1
    elif e[i][1]=="S3":
        arr[int(e[i][0][1:2])-1][2]=arr[int(e[i][0][1:2])-1][2]+1
        s3=s3+1
for i in  range(5):
    print("P(F=",g[i],"|S==S1)=",arr[i][0],"/",s1)
for i in  range(5):
    print("P(F=",g[i],"|S==S2)=",arr[i][1],"/",s2)
for i in  range(5):
    print("P(F=",g[i],"|S==S3)=",arr[i][2],"/",s3)




                

P(F= F1 |S==S1)= 1 / 4
P(F= F2 |S==S1)= 1 / 4
P(F= F3 |S==S1)= 0 / 4
P(F= F4 |S==S1)= 1 / 4
P(F= F5 |S==S1)= 1 / 4
P(F= F1 |S==S2)= 1 / 3
P(F= F2 |S==S2)= 1 / 3
P(F= F3 |S==S2)= 1 / 3
P(F= F4 |S==S2)= 0 / 3
P(F= F5 |S==S2)= 0 / 3
P(F= F1 |S==S3)= 0 / 3
P(F= F2 |S==S3)= 1 / 3
P(F= F3 |S==S3)= 1 / 3
P(F= F4 |S==S3)= 1 / 3
P(F= F5 |S==S3)= 0 / 3


<h3> Q9: Operations on sentences </h3>

You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 unique values"
S2= "the second column S will contain only 3 unique values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [ ]:
# Input of the two sentences
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Sa = S1.split()
Sb = S2.split()
f = []
#  Number of common words between S1, S2
for i in range(0,len(Sa)):
    for j in range(0,len(Sb)):
        
        if Sa[i]==Sb[j]:
            f.append(Sa[i])
print(' Number of common words between S1, S2 =',len(f))
l = []
#  Words in S1 but not in S2
for i in range(0,len(Sa)):
    if Sa[i] not in f:
        l.append(Sa[i])
print(' Words in S1 but not in S2',l)
# Words in S2 but not in S1
k = []
for i in range(0,len(Sb)):
    if Sb[i] not in f:
        k.append(Sb[i])
print('Words in S2 but not in S1',k)


 Number of common words between S1, S2 = 7
 Words in S1 but not in S2 ['first', 'F', '5']
Words in S2 but not in S1 ['second', 'S', '3']


<h3> Q10: Error Function</h3>

You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.44982
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [ ]:
import math
# input list
o = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
print(len(o))
u = 0
for i in range(0,len(o)):
    u += (o[i][0]*math.log10(o[i][1])+(1-o[i][0])*math.log10(1-o[i][1]))
print(u)
print(float((-1/len(o))*(u)))

8
-3.394479476562531
0.42430993457031635
